<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Vishman" failures="3" tests="6" name="FireFoxTest" time="67.015" errors="0" timestamp="2024-08-23T22:35:20 IST">
  <testcase classname="testCases.LoginPageTest" name="loginDatas" time="0.213"/>
  <testcase classname="testCases.LoginPageTest" name="verifyLoginWithValidData" time="1.018"/>
  <testcase classname="testCases.LoginPageTest" name="verifyWithAllData" time="0.669">
    <failure type="java.lang.AssertionError" message="Alert message is not Available expected [Alert!1] but found [Alert!]">
      <![CDATA[java.lang.AssertionError: Alert message is not Available expected [Alert!1] but found [Alert!]
at testCases.LoginPageTest.verifyWithAllData(LoginPageTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verifyWithAllData -->
  <testcase classname="testCases.LoginPageTest" name="verifyWithAllData" time="0.601">
    <failure type="java.lang.AssertionError" message="Alert message is not Available expected [Alert!1] but found [Alert!]">
      <![CDATA[java.lang.AssertionError: Alert message is not Available expected [Alert!1] but found [Alert!]
at testCases.LoginPageTest.verifyWithAllData(LoginPageTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verifyWithAllData -->
  <testcase classname="testCases.LoginPageTest" name="verifyWithAllData" time="0.674">
    <failure type="java.lang.AssertionError" message="Alert message is not Available expected [Alert!1] but found [Alert!]">
      <![CDATA[java.lang.AssertionError: Alert message is not Available expected [Alert!1] but found [Alert!]
at testCases.LoginPageTest.verifyWithAllData(LoginPageTest.java:39)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 23 stack frames]]>
    </failure>
  </testcase> <!-- verifyWithAllData -->
  <testcase classname="testCases.HomePageTest" name="verifyAllButton" time="1.425"/>
</testsuite> <!-- FireFoxTest -->
